### PR TITLE
Fix #58: Fix SSH authentication.

### LINKED ISSUE #58: SSH authentication doesn't work
The controller doesn't work with key-authenticated private repositories.

## Example

```
apiVersion: terraformcontroller.cattle.io/v1
kind: Module
metadata:
  name: test-module
  namespace: terraform-controller
spec:
  git:
    url: git@github.com:farkasmate/tf-test.git
    secretName: test-key

---
apiVersion: v1
kind: Secret
metadata:
  name: test-key
  namespace: terraform-controller
type: Opaque
data:
  ssh-privatekey: <snip>
```

## Behaviour

- The controller parses the k8s secret holding the SSH private key, but fails to persist it due to passing value in `fromSecret` rather than a pointer
- There's a typo in the environment variable name: `GIT_SSH_COMAND`

### PR DESCRIPTION
**Pull request by farkasmate**
Fixing #58

### CODE REVIEW

**Comment by luthermonson** [comment]
@farkasmate sorry to sit on this so long, this git code was moved and put into gitwatcher (rancher/gitwatcher) and this typo is fixed there so probably will close this PR and open a new one with an import of the gitwatcher code instead of fixing this locally.

**Comment by farkasmate** [comment]
@luthermonson Sounds good.

**Comment by docteurklein** [comment]
I'm not sure this is fixed, since this repo doesn't use gitwatcher as a dependency. Currently the typo is still executed.

**Comment by farkasmate** [comment]
@docteurklein I close this PR, not going to be merged. Make a fork and patch it if you still use this project.

**Pull request closed without merging**
